import './globals.css'
import type { Metadata } from 'next'
import { Catamaran } from 'next/font/google'
const cataraman = Catamaran({
  subsets: ['latin-ext'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})
 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${cataraman.className} text-[#434546]`}>{children}</body>
    </html>
  )
}
